### PR TITLE
Feature/contact us UI

### PR DESCRIPTION
**Pull request by NagasaiBharat**

### CODE REVIEW

**Review by ravishankar63 — COMMENTED** [review]
"The code looks fine bro. Do check for all the functionalities if working well (Zoom in/out, width change)" then we can merge it.

**Comment by NagasaiBharat** [comment]
>

**Comment by NagasaiBharat** [comment]
Applied breakpoints. Looks good now.

**Comment by ravishankar63** [comment]
Looks fine. Lmk we can close PR

**Comment by ravishankar63** [comment]
You can put the forms  under elements folder and then import

**Comment by NagasaiBharat** [comment]
Added elements folder

**Comment by ravishankar63** [comment]
"Done"

**Review by ravishankar63 — APPROVED** [review]
"Approved"

**Pull request merged**
